SET NAMES utf8mb4;
SET time_zone = '+00:00';

CREATE TABLE IF NOT EXISTS backup_policies (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_id VARCHAR(48) NOT NULL,
    account_id BIGINT UNSIGNED NOT NULL,
    target_type ENUM('pod','homeserver') NOT NULL,
    pod_deployment_id BIGINT UNSIGNED NULL,
    homeserver_device_id BIGINT UNSIGNED NULL,
    status ENUM('active','paused','retired') NOT NULL DEFAULT 'active',
    schedule_interval_minutes INT UNSIGNED NOT NULL DEFAULT 1440,
    retention_count INT UNSIGNED NOT NULL DEFAULT 14,
    retention_days INT UNSIGNED NOT NULL DEFAULT 30,
    require_verification TINYINT(1) NOT NULL DEFAULT 1,
    next_run_at DATETIME NULL,
    last_run_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE KEY uq_backup_policy_public (public_id),
    UNIQUE KEY uq_backup_policy_pod (pod_deployment_id),
    UNIQUE KEY uq_backup_policy_homeserver (homeserver_device_id),
    KEY idx_backup_policy_due (status, next_run_at),
    CONSTRAINT fk_backup_policy_account FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE RESTRICT,
    CONSTRAINT fk_backup_policy_pod FOREIGN KEY (pod_deployment_id) REFERENCES pod_deployments(id) ON DELETE RESTRICT,
    CONSTRAINT fk_backup_policy_homeserver FOREIGN KEY (homeserver_device_id) REFERENCES homeserver_devices(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS backup_jobs (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_id VARCHAR(48) NOT NULL,
    account_id BIGINT UNSIGNED NOT NULL,
    policy_id BIGINT UNSIGNED NULL,
    target_type ENUM('pod','homeserver') NOT NULL,
    pod_deployment_id BIGINT UNSIGNED NULL,
    homeserver_device_id BIGINT UNSIGNED NULL,
    job_type ENUM('scheduled','on_demand','pre_update','retention_delete') NOT NULL,
    status ENUM('queued','running','creating','verifying','completed','failed','paused','canceled') NOT NULL DEFAULT 'queued',
    idempotency_key VARCHAR(128) NOT NULL,
    request_id VARCHAR(64) NOT NULL,
    attempts SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    max_attempts SMALLINT UNSIGNED NOT NULL DEFAULT 5,
    available_at DATETIME NOT NULL,
    locked_at DATETIME NULL,
    locked_by VARCHAR(128) NULL,
    started_at DATETIME NULL,
    completed_at DATETIME NULL,
    last_error_code VARCHAR(100) NULL,
    last_error_message VARCHAR(1000) NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE KEY uq_backup_job_public (public_id),
    UNIQUE KEY uq_backup_job_idempotency (account_id, idempotency_key),
    KEY idx_backup_job_claim (status, available_at, id),
    CONSTRAINT fk_backup_job_account FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE RESTRICT,
    CONSTRAINT fk_backup_job_policy FOREIGN KEY (policy_id) REFERENCES backup_policies(id) ON DELETE SET NULL,
    CONSTRAINT fk_backup_job_pod FOREIGN KEY (pod_deployment_id) REFERENCES pod_deployments(id) ON DELETE RESTRICT,
    CONSTRAINT fk_backup_job_homeserver FOREIGN KEY (homeserver_device_id) REFERENCES homeserver_devices(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS backup_snapshots (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_id VARCHAR(48) NOT NULL,
    account_id BIGINT UNSIGNED NOT NULL,
    backup_job_id BIGINT UNSIGNED NOT NULL,
    target_type ENUM('pod','homeserver') NOT NULL,
    pod_deployment_id BIGINT UNSIGNED NULL,
    homeserver_device_id BIGINT UNSIGNED NULL,
    status ENUM('pending_verification','verified','failed','expired','deleted') NOT NULL DEFAULT 'pending_verification',
    snapshot_hash CHAR(64) NOT NULL,
    provider_reference_ciphertext LONGTEXT NOT NULL,
    provider_reference_nonce VARCHAR(64) NOT NULL,
    provider_reference_tag VARCHAR(64) NOT NULL,
    encryption_key_id VARCHAR(80) NOT NULL,
    size_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
    verification_status ENUM('pending','verified','failed') NOT NULL DEFAULT 'pending',
    verified_at DATETIME NULL,
    expires_at DATETIME NULL,
    deleted_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE KEY uq_backup_snapshot_public (public_id),
    UNIQUE KEY uq_backup_snapshot_hash (target_type, snapshot_hash),
    KEY idx_backup_snapshot_retention (status, expires_at),
    KEY idx_backup_snapshot_account_time (account_id, created_at),
    CONSTRAINT fk_backup_snapshot_account FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE RESTRICT,
    CONSTRAINT fk_backup_snapshot_job FOREIGN KEY (backup_job_id) REFERENCES backup_jobs(id) ON DELETE RESTRICT,
    CONSTRAINT fk_backup_snapshot_pod FOREIGN KEY (pod_deployment_id) REFERENCES pod_deployments(id) ON DELETE RESTRICT,
    CONSTRAINT fk_backup_snapshot_homeserver FOREIGN KEY (homeserver_device_id) REFERENCES homeserver_devices(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS backup_verifications (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    snapshot_id BIGINT UNSIGNED NOT NULL,
    backup_job_id BIGINT UNSIGNED NOT NULL,
    result ENUM('verified','failed') NOT NULL,
    verification_hash CHAR(64) NOT NULL,
    checked_at DATETIME NOT NULL,
    metadata_json JSON NULL,
    KEY idx_backup_verification_snapshot_time (snapshot_id, checked_at),
    CONSTRAINT fk_backup_verification_snapshot FOREIGN KEY (snapshot_id) REFERENCES backup_snapshots(id) ON DELETE CASCADE,
    CONSTRAINT fk_backup_verification_job FOREIGN KEY (backup_job_id) REFERENCES backup_jobs(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS restore_jobs (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_id VARCHAR(48) NOT NULL,
    account_id BIGINT UNSIGNED NOT NULL,
    snapshot_id BIGINT UNSIGNED NOT NULL,
    status ENUM('queued','running','validating','restoring','verifying','completed','failed','paused','canceled') NOT NULL DEFAULT 'queued',
    idempotency_key VARCHAR(128) NOT NULL,
    request_id VARCHAR(64) NOT NULL,
    attempts SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    max_attempts SMALLINT UNSIGNED NOT NULL DEFAULT 3,
    available_at DATETIME NOT NULL,
    locked_at DATETIME NULL,
    locked_by VARCHAR(128) NULL,
    started_at DATETIME NULL,
    completed_at DATETIME NULL,
    last_error_code VARCHAR(100) NULL,
    last_error_message VARCHAR(1000) NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE KEY uq_restore_job_public (public_id),
    UNIQUE KEY uq_restore_job_idempotency (account_id, idempotency_key),
    KEY idx_restore_job_claim (status, available_at, id),
    CONSTRAINT fk_restore_job_account FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE RESTRICT,
    CONSTRAINT fk_restore_job_snapshot FOREIGN KEY (snapshot_id) REFERENCES backup_snapshots(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS backup_receipts (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_id VARCHAR(48) NOT NULL,
    account_id BIGINT UNSIGNED NOT NULL,
    backup_job_id BIGINT UNSIGNED NULL,
    restore_job_id BIGINT UNSIGNED NULL,
    snapshot_id BIGINT UNSIGNED NULL,
    request_id VARCHAR(64) NOT NULL,
    operation VARCHAR(100) NOT NULL,
    result ENUM('success','failure','denied','ignored') NOT NULL,
    receipt_hash CHAR(64) NULL,
    metadata_json JSON NULL,
    created_at DATETIME NOT NULL,
    UNIQUE KEY uq_backup_receipt_public (public_id),
    KEY idx_backup_receipt_account_time (account_id, created_at),
    CONSTRAINT fk_backup_receipt_account FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE RESTRICT,
    CONSTRAINT fk_backup_receipt_backup_job FOREIGN KEY (backup_job_id) REFERENCES backup_jobs(id) ON DELETE SET NULL,
    CONSTRAINT fk_backup_receipt_restore_job FOREIGN KEY (restore_job_id) REFERENCES restore_jobs(id) ON DELETE SET NULL,
    CONSTRAINT fk_backup_receipt_snapshot FOREIGN KEY (snapshot_id) REFERENCES backup_snapshots(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS storage_observations (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    account_id BIGINT UNSIGNED NOT NULL,
    target_type ENUM('pod','homeserver') NOT NULL,
    pod_deployment_id BIGINT UNSIGNED NULL,
    homeserver_device_id BIGINT UNSIGNED NULL,
    usage_bytes BIGINT UNSIGNED NOT NULL,
    allowance_bytes BIGINT UNSIGNED NOT NULL,
    utilization_percent DECIMAL(6,2) NOT NULL,
    observed_at DATETIME NOT NULL,
    KEY idx_storage_observation_account_time (account_id, observed_at),
    KEY idx_storage_observation_pod_time (pod_deployment_id, observed_at),
    KEY idx_storage_observation_homeserver_time (homeserver_device_id, observed_at),
    CONSTRAINT fk_storage_observation_account FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE RESTRICT,
    CONSTRAINT fk_storage_observation_pod FOREIGN KEY (pod_deployment_id) REFERENCES pod_deployments(id) ON DELETE RESTRICT,
    CONSTRAINT fk_storage_observation_homeserver FOREIGN KEY (homeserver_device_id) REFERENCES homeserver_devices(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS storage_alerts (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_id VARCHAR(48) NOT NULL,
    account_id BIGINT UNSIGNED NOT NULL,
    observation_id BIGINT UNSIGNED NOT NULL,
    severity ENUM('warning','critical') NOT NULL,
    status ENUM('open','acknowledged','resolved') NOT NULL DEFAULT 'open',
    threshold_percent DECIMAL(6,2) NOT NULL,
    opened_at DATETIME NOT NULL,
    acknowledged_at DATETIME NULL,
    resolved_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE KEY uq_storage_alert_public (public_id),
    KEY idx_storage_alert_account_status (account_id, status),
    CONSTRAINT fk_storage_alert_account FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE RESTRICT,
    CONSTRAINT fk_storage_alert_observation FOREIGN KEY (observation_id) REFERENCES storage_observations(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
