SET NAMES utf8mb4;
SET time_zone = '+00:00';

CREATE TABLE IF NOT EXISTS pod_deployments (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_id VARCHAR(48) NOT NULL,
    account_id BIGINT UNSIGNED NOT NULL,
    subscription_id BIGINT UNSIGNED NOT NULL,
    domain_registration_id BIGINT UNSIGNED NOT NULL,
    license_id BIGINT UNSIGNED NOT NULL,
    status ENUM('pending','provisioning','active','degraded','suspended','failed','archived') NOT NULL DEFAULT 'pending',
    installation_fingerprint CHAR(64) NOT NULL,
    hosting_reference VARCHAR(190) NULL,
    database_reference VARCHAR(190) NULL,
    installed_version VARCHAR(80) NULL,
    update_channel VARCHAR(32) NOT NULL DEFAULT 'stable',
    storage_usage_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
    storage_allowance_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
    last_heartbeat_at DATETIME NULL,
    routing_status ENUM('pending','active','degraded','disabled') NOT NULL DEFAULT 'pending',
    ssl_status ENUM('pending','active','renewing','failed','disabled') NOT NULL DEFAULT 'pending',
    backup_status ENUM('unknown','pending','verified','failed','disabled') NOT NULL DEFAULT 'unknown',
    license_status ENUM('pending','active','grace','suspended','expired','terminated') NOT NULL DEFAULT 'pending',
    activated_at DATETIME NULL,
    suspended_at DATETIME NULL,
    archived_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE KEY uq_pod_deployment_public (public_id),
    UNIQUE KEY uq_pod_deployment_domain (domain_registration_id),
    UNIQUE KEY uq_pod_deployment_license (license_id),
    KEY idx_pod_deployment_account_status (account_id, status),
    KEY idx_pod_deployment_heartbeat (status, last_heartbeat_at),
    CONSTRAINT fk_pod_deployment_account FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE RESTRICT,
    CONSTRAINT fk_pod_deployment_subscription FOREIGN KEY (subscription_id) REFERENCES subscriptions(id) ON DELETE RESTRICT,
    CONSTRAINT fk_pod_deployment_domain FOREIGN KEY (domain_registration_id) REFERENCES domain_registrations(id) ON DELETE RESTRICT,
    CONSTRAINT fk_pod_deployment_license FOREIGN KEY (license_id) REFERENCES licenses(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pod_provisioning_jobs (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_id VARCHAR(48) NOT NULL,
    deployment_id BIGINT UNSIGNED NOT NULL,
    account_id BIGINT UNSIGNED NOT NULL,
    job_type ENUM('provision','rollback') NOT NULL DEFAULT 'provision',
    status ENUM('queued','running','waiting','retrying','paused','completed','failed','canceled') NOT NULL DEFAULT 'queued',
    current_stage VARCHAR(80) NULL,
    attempts SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    max_attempts SMALLINT UNSIGNED NOT NULL DEFAULT 5,
    idempotency_key VARCHAR(128) NOT NULL,
    request_id VARCHAR(64) NOT NULL,
    available_at DATETIME NOT NULL,
    locked_at DATETIME NULL,
    locked_by VARCHAR(128) NULL,
    started_at DATETIME NULL,
    completed_at DATETIME NULL,
    last_error_code VARCHAR(100) NULL,
    last_error_message VARCHAR(1000) NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE KEY uq_pod_job_public (public_id),
    UNIQUE KEY uq_pod_job_idempotency (account_id, idempotency_key),
    KEY idx_pod_job_claim (status, available_at, id),
    KEY idx_pod_job_deployment (deployment_id, created_at),
    CONSTRAINT fk_pod_job_deployment FOREIGN KEY (deployment_id) REFERENCES pod_deployments(id) ON DELETE CASCADE,
    CONSTRAINT fk_pod_job_account FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pod_provisioning_steps (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    job_id BIGINT UNSIGNED NOT NULL,
    deployment_id BIGINT UNSIGNED NOT NULL,
    stage VARCHAR(80) NOT NULL,
    sequence_no SMALLINT UNSIGNED NOT NULL,
    status ENUM('pending','running','completed','failed','skipped','rolled_back') NOT NULL DEFAULT 'pending',
    attempts SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    provider_receipt_hash CHAR(64) NULL,
    started_at DATETIME NULL,
    completed_at DATETIME NULL,
    rolled_back_at DATETIME NULL,
    last_error_code VARCHAR(100) NULL,
    last_error_message VARCHAR(1000) NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE KEY uq_pod_step_job_stage (job_id, stage),
    UNIQUE KEY uq_pod_step_job_sequence (job_id, sequence_no),
    KEY idx_pod_step_deployment (deployment_id, sequence_no),
    CONSTRAINT fk_pod_step_job FOREIGN KEY (job_id) REFERENCES pod_provisioning_jobs(id) ON DELETE CASCADE,
    CONSTRAINT fk_pod_step_deployment FOREIGN KEY (deployment_id) REFERENCES pod_deployments(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pod_provisioning_receipts (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_id VARCHAR(48) NOT NULL,
    account_id BIGINT UNSIGNED NOT NULL,
    deployment_id BIGINT UNSIGNED NOT NULL,
    job_id BIGINT UNSIGNED NOT NULL,
    step_id BIGINT UNSIGNED NULL,
    request_id VARCHAR(64) NOT NULL,
    operation VARCHAR(100) NOT NULL,
    result ENUM('success','failure','ignored','denied') NOT NULL,
    external_reference_hash CHAR(64) NULL,
    metadata_json JSON NULL,
    created_at DATETIME NOT NULL,
    UNIQUE KEY uq_pod_receipt_public (public_id),
    KEY idx_pod_receipt_account_time (account_id, created_at),
    KEY idx_pod_receipt_job (job_id, created_at),
    CONSTRAINT fk_pod_receipt_account FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE RESTRICT,
    CONSTRAINT fk_pod_receipt_deployment FOREIGN KEY (deployment_id) REFERENCES pod_deployments(id) ON DELETE CASCADE,
    CONSTRAINT fk_pod_receipt_job FOREIGN KEY (job_id) REFERENCES pod_provisioning_jobs(id) ON DELETE CASCADE,
    CONSTRAINT fk_pod_receipt_step FOREIGN KEY (step_id) REFERENCES pod_provisioning_steps(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pod_configuration_receipts (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    deployment_id BIGINT UNSIGNED NOT NULL,
    job_id BIGINT UNSIGNED NOT NULL,
    configuration_hash CHAR(64) NOT NULL,
    protected_roots_hash CHAR(64) NOT NULL,
    merge_strategy VARCHAR(80) NOT NULL DEFAULT 'preserve-existing-protected-paths',
    created_at DATETIME NOT NULL,
    KEY idx_pod_configuration_deployment (deployment_id, created_at),
    CONSTRAINT fk_pod_configuration_deployment FOREIGN KEY (deployment_id) REFERENCES pod_deployments(id) ON DELETE CASCADE,
    CONSTRAINT fk_pod_configuration_job FOREIGN KEY (job_id) REFERENCES pod_provisioning_jobs(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pod_deployment_events (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    deployment_id BIGINT UNSIGNED NOT NULL,
    account_id BIGINT UNSIGNED NOT NULL,
    request_id VARCHAR(64) NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    result ENUM('success','failure','denied') NOT NULL,
    from_status VARCHAR(32) NULL,
    to_status VARCHAR(32) NULL,
    metadata_json JSON NULL,
    created_at DATETIME NOT NULL,
    KEY idx_pod_event_deployment_time (deployment_id, created_at),
    KEY idx_pod_event_account_time (account_id, created_at),
    CONSTRAINT fk_pod_event_deployment FOREIGN KEY (deployment_id) REFERENCES pod_deployments(id) ON DELETE CASCADE,
    CONSTRAINT fk_pod_event_account FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
