<?php

declare(strict_types=1);

return [
    'app' => [
        'name' => 'VP3.me',
        'env' => getenv('APP_ENV') ?: 'development',
        'base_url' => rtrim((string) (getenv('APP_BASE_URL') ?: 'https://vp3.me'), '/'),
        'session_name' => getenv('APP_SESSION_NAME') ?: 'vp3_session',
        'session_secure' => filter_var(getenv('APP_SESSION_SECURE') ?: '1', FILTER_VALIDATE_BOOL),
    ],
    'database' => [
        'dsn' => getenv('DB_DSN') ?: 'mysql:host=127.0.0.1;dbname=vp3;charset=utf8mb4',
        'username' => getenv('DB_USERNAME') ?: 'vp3',
        'password' => getenv('DB_PASSWORD') ?: '',
        'options' => [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            PDO::ATTR_EMULATE_PREPARES => false,
        ],
    ],
    'auth' => [
        'password_min_length' => 12,
        'verification_ttl_seconds' => max(300, (int) (getenv('AUTH_VERIFICATION_TTL_SECONDS') ?: 86400)),
        'password_reset_ttl_seconds' => max(300, (int) (getenv('AUTH_PASSWORD_RESET_TTL_SECONDS') ?: 3600)),
        'login_attempt_limit' => max(1, (int) (getenv('AUTH_LOGIN_ATTEMPT_LIMIT') ?: 8)),
        'login_attempt_window_seconds' => max(60, (int) (getenv('AUTH_LOGIN_ATTEMPT_WINDOW_SECONDS') ?: 900)),
        'session_inactivity_ttl_seconds' => max(300, (int) (getenv('AUTH_SESSION_INACTIVITY_TTL_SECONDS') ?: 1800)),
        'session_absolute_ttl_seconds' => max(600, (int) (getenv('AUTH_SESSION_ABSOLUTE_TTL_SECONDS') ?: 43200)),
    ],
    'mail' => [
        'driver' => strtolower((string) (getenv('MAIL_DRIVER') ?: 'null')),
        'smtp_host' => (string) (getenv('SMTP_HOST') ?: ''),
        'smtp_port' => max(1, (int) (getenv('SMTP_PORT') ?: 587)),
        'smtp_encryption' => strtolower((string) (getenv('SMTP_ENCRYPTION') ?: 'tls')),
        'smtp_username' => (string) (getenv('SMTP_USERNAME') ?: ''),
        'smtp_password' => (string) (getenv('SMTP_PASSWORD') ?: ''),
        'sender_email' => (string) (getenv('MAIL_SENDER_EMAIL') ?: 'no-reply@vp3.me'),
        'sender_name' => (string) (getenv('MAIL_SENDER_NAME') ?: 'VP3.me'),
    ],
    'stripe' => [
        'secret_key' => getenv('STRIPE_SECRET_KEY') ?: '',
        'webhook_secret' => getenv('STRIPE_WEBHOOK_SECRET') ?: '',
        'api_base' => rtrim((string) (getenv('STRIPE_API_BASE') ?: 'https://api.stripe.com/v1'), '/'),
        'signature_tolerance_seconds' => max(60, (int) (getenv('STRIPE_SIGNATURE_TOLERANCE_SECONDS') ?: 300)),
        'grace_days' => max(1, (int) (getenv('STRIPE_GRACE_DAYS') ?: 7)),
    ],
    'provisioning' => [
        'provider_driver' => strtolower((string) (getenv('VP3_PROVISIONING_DRIVER') ?: 'null')),
        'deployment_root' => (string) (getenv('VP3_POD_DEPLOYMENT_ROOT') ?: '/srv/vp3/pods'),
        'release_zip' => (string) (getenv('VP3_POD_RELEASE_ZIP') ?: '/srv/vp3/releases/pod.zip'),
        'release_version' => (string) (getenv('VP3_POD_RELEASE_VERSION') ?: 'development'),
        'release_sha256' => strtolower((string) (getenv('VP3_POD_RELEASE_SHA256') ?: '')),
        'configuration_path' => (string) (getenv('VP3_POD_CONFIGURATION_PATH') ?: 'config/config.php'),
        'entrypoint_path' => (string) (getenv('VP3_POD_ENTRYPOINT_PATH') ?: 'public/index.php'),
        'wildcard_base_domain' => strtolower((string) (getenv('VP3_WILDCARD_BASE_DOMAIN') ?: 'vp3.me')),
        'wildcard_tls_ready' => filter_var(getenv('VP3_WILDCARD_TLS_READY') ?: '0', FILTER_VALIDATE_BOOL),
        'database_admin_dsn' => (string) (getenv('VP3_POD_DB_ADMIN_DSN') ?: 'mysql:host=127.0.0.1;charset=utf8mb4'),
        'database_admin_username' => (string) (getenv('VP3_POD_DB_ADMIN_USERNAME') ?: ''),
        'database_admin_password' => (string) (getenv('VP3_POD_DB_ADMIN_PASSWORD') ?: ''),
        'database_host' => (string) (getenv('VP3_POD_DB_HOST') ?: '127.0.0.1'),
        'database_port' => max(1, (int) (getenv('VP3_POD_DB_PORT') ?: 3306)),
        'database_charset' => strtolower((string) (getenv('VP3_POD_DB_CHARSET') ?: 'utf8mb4')),
        'database_name_prefix' => strtolower((string) (getenv('VP3_POD_DB_NAME_PREFIX') ?: 'vp3pod_')),
        'database_user_prefix' => strtolower((string) (getenv('VP3_POD_DB_USER_PREFIX') ?: 'vp3pod_')),
        'database_user_host' => (string) (getenv('VP3_POD_DB_USER_HOST') ?: 'localhost'),
        'maximum_archive_files' => max(1, (int) (getenv('VP3_POD_MAX_ARCHIVE_FILES') ?: 20000)),
        'maximum_archive_bytes' => max(1048576, (int) (getenv('VP3_POD_MAX_ARCHIVE_BYTES') ?: 1073741824)),
        'strip_single_root' => filter_var(getenv('VP3_POD_STRIP_SINGLE_ROOT') ?: '1', FILTER_VALIDATE_BOOL),
        'protected_configuration_paths' => array_values(array_filter(array_map(
            'trim',
            explode(',', getenv('VP3_PROTECTED_CONFIGURATION_PATHS') ?: 'database.password,app.key,customer')
        ))),
    ],
    'homeserver' => [
        'lease_signing_private_key_base64' => getenv('VP3_HOMESERVER_LEASE_PRIVATE_KEY_B64') ?: '',
        'lease_signing_public_key_base64' => getenv('VP3_HOMESERVER_LEASE_PUBLIC_KEY_B64') ?: '',
        'lease_signing_key_id' => getenv('VP3_HOMESERVER_LEASE_SIGNING_KEY_ID') ?: 'homeserver-lease-ed25519-v1',
        'pairing_ttl_seconds' => max(60, (int) (getenv('HOMESERVER_PAIRING_TTL_SECONDS') ?: 900)),
        'lease_ttl_seconds' => max(300, (int) (getenv('HOMESERVER_LEASE_TTL_SECONDS') ?: 3600)),
        'offline_after_minutes' => max(1, (int) (getenv('HOMESERVER_OFFLINE_AFTER_MINUTES') ?: 10)),
    ],
    'releases' => [
        'signing_private_key_base64' => getenv('RELEASE_SIGNING_PRIVATE_KEY_B64') ?: '',
        'signing_public_key_base64' => getenv('RELEASE_SIGNING_PUBLIC_KEY_B64') ?: '',
        'signing_key_id' => getenv('RELEASE_SIGNING_KEY_ID') ?: 'release-ed25519-v1',
        'update_provider_driver' => strtolower((string) (getenv('VP3_UPDATE_PROVIDER_DRIVER') ?: 'null')),
        'deployment_root' => (string) (getenv('VP3_POD_DEPLOYMENT_ROOT') ?: '/srv/vp3/pods'),
        'backup_root' => (string) (getenv('VP3_LOCAL_BACKUP_ROOT') ?: '/srv/vp3/backups'),
        'backup_encryption_key_base64' => (string) (getenv('VP3_LOCAL_BACKUP_ENCRYPTION_KEY_B64') ?: ''),
        'configuration_path' => (string) (getenv('VP3_POD_CONFIGURATION_PATH') ?: 'config/config.php'),
        'entrypoint_path' => (string) (getenv('VP3_POD_ENTRYPOINT_PATH') ?: 'public/index.php'),
        'mysqldump_binary' => (string) (getenv('VP3_MYSQLDUMP_BINARY') ?: '/usr/bin/mysqldump'),
        'mysql_binary' => (string) (getenv('VP3_MYSQL_BINARY') ?: '/usr/bin/mysql'),
        'database_host' => (string) (getenv('VP3_POD_DB_HOST') ?: '127.0.0.1'),
        'database_port' => max(1, (int) (getenv('VP3_POD_DB_PORT') ?: 3306)),
        'maximum_archive_files' => max(1, (int) (getenv('VP3_POD_MAX_ARCHIVE_FILES') ?: 20000)),
        'maximum_archive_bytes' => max(1048576, (int) (getenv('VP3_POD_MAX_ARCHIVE_BYTES') ?: 1073741824)),
        'maximum_backup_bytes' => max(1048576, (int) (getenv('VP3_LOCAL_BACKUP_MAX_BYTES') ?: 5368709120)),
    ],
    'backups' => [
        'metadata_encryption_key_base64' => getenv('BACKUP_METADATA_ENCRYPTION_KEY_B64') ?: '',
        'metadata_encryption_key_id' => getenv('BACKUP_METADATA_ENCRYPTION_KEY_ID') ?: 'backup-aes256gcm-v1',
        'provider_driver' => strtolower((string) (getenv('VP3_BACKUP_PROVIDER_DRIVER') ?: 'null')),
        'deployment_root' => (string) (getenv('VP3_POD_DEPLOYMENT_ROOT') ?: '/srv/vp3/pods'),
        'local_backup_root' => (string) (getenv('VP3_LOCAL_BACKUP_ROOT') ?: '/srv/vp3/backups'),
        'local_encryption_key_base64' => (string) (getenv('VP3_LOCAL_BACKUP_ENCRYPTION_KEY_B64') ?: ''),
        'configuration_path' => (string) (getenv('VP3_POD_CONFIGURATION_PATH') ?: 'config/config.php'),
        'mysqldump_binary' => (string) (getenv('VP3_MYSQLDUMP_BINARY') ?: '/usr/bin/mysqldump'),
        'mysql_binary' => (string) (getenv('VP3_MYSQL_BINARY') ?: '/usr/bin/mysql'),
        'database_host' => (string) (getenv('VP3_POD_DB_HOST') ?: '127.0.0.1'),
        'database_port' => max(1, (int) (getenv('VP3_POD_DB_PORT') ?: 3306)),
        'maximum_backup_bytes' => max(1048576, (int) (getenv('VP3_LOCAL_BACKUP_MAX_BYTES') ?: 5368709120)),
        'warning_threshold_percent' => min(100.0, max(1.0, (float) (getenv('STORAGE_WARNING_THRESHOLD_PERCENT') ?: 80))),
        'critical_threshold_percent' => min(100.0, max(1.0, (float) (getenv('STORAGE_CRITICAL_THRESHOLD_PERCENT') ?: 95))),
    ],
    'infrastructure' => [
        'provider_driver' => strtolower((string) (getenv('VP3_INFRASTRUCTURE_PROVIDER_DRIVER') ?: 'null')),
        'secret_encryption_key_base64' => getenv('PROVIDER_SECRET_ENCRYPTION_KEY_B64') ?: '',
        'secret_encryption_key_id' => getenv('PROVIDER_SECRET_ENCRYPTION_KEY_ID') ?: 'provider-aes256gcm-v1',
        'deployment_root' => (string) (getenv('VP3_POD_DEPLOYMENT_ROOT') ?: '/srv/vp3/pods'),
        'wildcard_base_domain' => strtolower((string) (getenv('VP3_WILDCARD_BASE_DOMAIN') ?: 'vp3.me')),
        'wildcard_dns_ready' => filter_var(getenv('VP3_WILDCARD_DNS_READY') ?: '0', FILTER_VALIDATE_BOOL),
        'wildcard_tls_ready' => filter_var(getenv('VP3_WILDCARD_TLS_READY') ?: '0', FILTER_VALIDATE_BOOL),
    ],
    'queue' => [
        'lease_seconds' => (int) (getenv('VP3_QUEUE_LEASE_SECONDS') ?: 900),
    ],
    'operations' => [
        'notification_driver' => strtolower((string) (getenv('VP3_OPERATIONS_NOTIFICATION_DRIVER') ?: 'null')),
        'secret_encryption_key_base64' => getenv('OPERATIONS_SECRET_ENCRYPTION_KEY_B64') ?: '',
        'secret_encryption_key_id' => getenv('OPERATIONS_SECRET_ENCRYPTION_KEY_ID') ?: 'operations-aes256gcm-v1',
        'pod_offline_after_minutes' => max(1, (int) (getenv('OPERATIONS_POD_OFFLINE_AFTER_MINUTES') ?: 10)),
        'homeserver_offline_after_minutes' => max(1, (int) (getenv('OPERATIONS_HOMESERVER_OFFLINE_AFTER_MINUTES') ?: 10)),
    ],
];
