<?php

declare(strict_types=1);

$root = dirname(__DIR__);
$databaseRoot = $root . '/database';
$manifestPath = $databaseRoot . '/single-install-manifest.txt';
$outputPath = $databaseRoot . '/vp3-single-install.sql';

if (!is_file($manifestPath)) {
    fwrite(STDERR, "Missing installer manifest: {$manifestPath}\n");
    exit(1);
}

$lines = file($manifestPath, FILE_IGNORE_NEW_LINES);
if (!is_array($lines)) {
    fwrite(STDERR, "Unable to read installer manifest.\n");
    exit(1);
}

$migrations = [];
foreach ($lines as $line) {
    $line = trim($line);
    if ($line === '' || str_starts_with($line, '#')) {
        continue;
    }
    if (str_contains($line, '..') || str_starts_with($line, '/') || str_starts_with($line, '\\')) {
        fwrite(STDERR, "Unsafe migration path in manifest: {$line}\n");
        exit(1);
    }
    $path = $databaseRoot . '/' . str_replace('\\', '/', $line);
    if (!is_file($path)) {
        fwrite(STDERR, "Missing migration listed in manifest: {$line}\n");
        exit(1);
    }
    $migrations[] = [$line, $path];
}

if ($migrations === []) {
    fwrite(STDERR, "The installer manifest is empty.\n");
    exit(1);
}

$generatedAt = gmdate('Y-m-d\TH:i:s\Z');
$parts = [
    "-- VP3 cumulative standalone database installer",
    "-- Generated by tools/build-single-install.php",
    "-- Generated at {$generatedAt}",
    "-- Import this single file into an empty MySQL 8 or MariaDB 10.11 database.",
    "",
    "SET NAMES utf8mb4;",
    "SET time_zone = '+00:00';",
    "SET FOREIGN_KEY_CHECKS = 0;",
    "",
];

foreach ($migrations as [$relativePath, $path]) {
    $content = file_get_contents($path);
    if (!is_string($content)) {
        fwrite(STDERR, "Unable to read migration: {$relativePath}\n");
        exit(1);
    }
    $content = preg_replace('/^\xEF\xBB\xBF/', '', $content) ?? $content;
    $content = str_replace(["\r\n", "\r"], "\n", $content);
    $content = preg_replace('/^SET NAMES utf8mb4;\n?/mi', '', $content) ?? $content;
    $content = preg_replace("/^SET time_zone = '\\+00:00';\n?/mi", '', $content) ?? $content;
    $content = trim($content);
    if (preg_match('/^\s*SOURCE\s+/mi', $content) === 1) {
        fwrite(STDERR, "Nested SOURCE directive found in migration: {$relativePath}\n");
        exit(1);
    }
    $parts[] = "-- BEGIN {$relativePath}";
    $parts[] = $content;
    $parts[] = "-- END {$relativePath}";
    $parts[] = "";
}

$parts[] = "SET FOREIGN_KEY_CHECKS = 1;";
$parts[] = "";
$output = implode("\n", $parts);

if (preg_match('/^\s*SOURCE\s+/mi', $output) === 1) {
    fwrite(STDERR, "Generated installer unexpectedly contains a SOURCE directive.\n");
    exit(1);
}

$tempPath = $outputPath . '.tmp';
if (file_put_contents($tempPath, $output, LOCK_EX) === false) {
    fwrite(STDERR, "Unable to write generated installer.\n");
    exit(1);
}
if (!rename($tempPath, $outputPath)) {
    @unlink($tempPath);
    fwrite(STDERR, "Unable to replace generated installer.\n");
    exit(1);
}

fwrite(STDOUT, sprintf(
    "Generated %s from %d migrations (%d bytes, sha256 %s).\n",
    $outputPath,
    count($migrations),
    strlen($output),
    hash('sha256', $output)
));
